name: Create File

on:
  push:
    branches:
      - main
    paths:
      - 'images/*.jpg'  # This triggers the action when JPG images are added/modified in the 'images' folder
     
  workflow_dispatch:


jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code to the runner

    - name: List JPG files in the images folder
      run: ls -l images/*.jpg  # List all jpg files in the 'images' folder

    - name: Generate HTML for Reveal.js Timelapse
      run: |
        # Create the HTML file with Reveal.js structure
        echo "<!DOCTYPE html>" > timelapse.html
        echo "<html lang=\"en\">" >> timelapse.html
        echo "<head>" >> timelapse.html
        echo "  <meta charset=\"UTF-8\">" >> timelapse.html
        echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> timelapse.html
        echo "  <title>Timelapse with Reveal.js</title>" >> timelapse.html
        echo "  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reveal.js@4.2.3/dist/reveal.css\">" >> timelapse.html
        echo "  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reveal.js@4.2.3/dist/theme/solarized.css\">" >> timelapse.html
        echo "  <script src=\"https://cdn.jsdelivr.net/npm/reveal.js@4.2.3/dist/reveal.min.js\"></script>" >> timelapse.html
        echo "</head>" >> timelapse.html
        echo "<body>" >> timelapse.html
        echo "  <div class=\"reveal\">" >> timelapse.html
        echo "    <div class=\"slides\">" >> timelapse.html

        # Loop over all jpg files and create a slide for each
        for img in images/*.jpg; do
          echo "      <section><img src=\"$img\" alt=\"Image\"></section>" >> timelapse.html
        done

        echo "    </div>" >> timelapse.html
        echo "  </div>" >> timelapse.html

        # Add Reveal.js initialization script
        echo "<script>" >> timelapse.html
        echo "  const deck = new Reveal();" >> timelapse.html
        echo "  deck.initialize();" >> timelapse.html
        echo "  setInterval(() => { deck.next(); }, 1000);" >> timelapse.html
        echo "</script>" >> timelapse.html

        echo "</body>" >> timelapse.html
        echo "</html>" >> timelapse.html
        mv ./timelapse.html ./index.html
        
      # Step 3: Commit and push the generated file
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: "Add .html with image list"
