name: Create File

on:
  schedule:
    - cron: '0 */12 * * *'   
  push:
    branches:
      - main
    paths:
      - 'images/*.jpg'  # This triggers the action when JPG images are added/modified in the 'images' folder
     
  workflow_dispatch:


jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code to the runner

    - name: List JPG files in the images folder
      run: ls -l images/*.jpg  # List all jpg files in the 'images' folder



    - name: Generate HTML for Reveal.js Timelapse
      run: |
        echo "<!DOCTYPE html>
        <html lang='en'>
        <head>
          <meta charset='UTF-8'>
          <meta name='viewport' content='width=device-width, initial-scale=1.0'>
          <title>Timelapse with Reveal.js</title>
          <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.3.1/reveal.css'>
          <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.3.1/theme/white.css'>
          <script src='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.3.1/reveal.js'></script>
        </head>
        <body>
          <div class='reveal'>
            <div class='slides' id='slides-container'></div>
            <script>
              document.addEventListener('DOMContentLoaded', function () {
                const slidesContainer = document.getElementById('slides-container');
                const images = '$(ls images/*.jpg | tr '\n' ',')'.split(',');
                images.forEach(img => {
                  const section = document.createElement('section');
                  const imageElement = document.createElement('img');
                  imageElement.src = img;
                  imageElement.alt = 'Image';
                  section.appendChild(imageElement);
                  slidesContainer.appendChild(section);
                });
                const deck = new Reveal();
                deck.initialize();
                setInterval(() => { deck.next(); }, 2000);
              });
            </script>
          </div>
        </body>
        </html>" > timelapse.html

        mv ./timelapse.html ./index.html


        
      # Step 3: Commit and push the generated file
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: "Add .html with image list"
