name: Download and Save Image with Timestamp

on:
  schedule:
    - cron:  "*/30 * * * *"   
  workflow_dispatch:  
  
jobs:
  download_image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download the image and rename it with a timestamp
      - name: Download image from URL and rename
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          MAX_RETRIES=5
          RETRY_COUNT=0
          SUCCESS=false

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            curl -o "image_${TIMESTAMP}.jpg" https://www.observatorioremoto.com/emadato/IPcam3.jpg
            FILE_SIZE=$(stat -c%s "image_${TIMESTAMP}.jpg")

            if [ $FILE_SIZE -ge 81920 ]; then
              SUCCESS=true
              break
            else
              echo "Downloaded image is less than 80kB, retrying..."
              rm "image_${TIMESTAMP}.jpg"
              RETRY_COUNT=$((RETRY_COUNT + 1))
            fi
          done

          if [ "$SUCCESS" = false ]; then
            echo "Failed to download a valid image after $MAX_RETRIES attempts."
            exit 1
          fi

      # Step 3: Commit and push the renamed image
      - name: Commit and push image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv image_*.jpg images/
          git add images/
          git commit -m "Add image downloaded at $TIMESTAMP"
          git push

