name: Download and Save Image with Timestamp

on:
  schedule:
    - cron:  "*/10 * * * *"   
  workflow_dispatch:  
  
jobs:
  download_image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download the image and rename it with a timestamp
      - name: Download image from URL and rename
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          curl -o "image_${TIMESTAMP}.jpg" https://www.observatorioremoto.com/emadato/IPcam3.jpg

      # Step 3: Commit and push the renamed image
      - name: Commit and push image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv image_*.jpg images/
          git add images/
          git commit -m "Add image downloaded at $TIMESTAMP"
          git push
